import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";


const saira = Saira({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Softconic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={saira.className}>
      <body className="antialiased ">
        {children}
        </body>
    </html>
  );
}
